# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Expense Tracker API Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      env:
        API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
        SPRING_USER: ${{ secrets.SPRING_USER }}
        SPRING_PASS: ${{ secrets.SPRING_PASS }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
      run: mvn -B package --file .github/expense-tracker-api/pom.xml
